Reduce nesting
We already exit early if detection succeeds, so no need to wrap error handling in an else clause

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -15,7 +15,7 @@ source "${BUILDPACK_DIR}/lib/output.sh"
 if find "${BUILD_DIR}" -maxdepth 1 -name "*.sln" -o -name "*.csproj" -o -name "*.fsproj" -o -name "*.vbproj" | grep -q .; then
 	echo ".NET"
 	exit 0
-else
-	output::error <<< 'Error: No .NET solution or project files (such as `foo.sln` or `foo.csproj`) found.'
-	exit 1
 fi
+
+output::error <<< 'Error: No .NET solution or project files (such as `foo.sln` or `foo.csproj`) found.'
+exit 1
